### PR TITLE
Tolerate additional pin protocols, unknown device features

### PR DESCRIPTION
**Pull request by shimunn**
Intended to address #2 @geneerik please try

### CODE REVIEW

**Comment by geneerik** [comment]
> Intended to address #2 @geneerik please try

I will give this a go. should work, but I will likely still hit the pin protocol issue as it has to do with how the accumulator is evaluated.  Would you be open to a pull request addressing this and adding parsing for some of the missing fields, even if not supported in the struct at the moment?  I could merge it with this branch for the "best of both worlds" and some future-proofing.

**Comment by shimunn** [comment]
> > Intended to address #2 @geneerik please try
> 
> I will give this a go. should work, but I will likely still hit the pin protocol issue as it has to do with how the accumulator is evaluated. Would you be open to a pull request addressing this and adding parsing for some of the missing fields, even if not supported in the struct at the moment? I could merge it with this branch for the "best of both worlds" and some future-proofing.

All that should be included in that commit, apart from storing the unused fields they're just skipped.

**Comment by geneerik** [comment]
> > > Intended to address #2 @geneerik please try
> > 
> > 
> > I will give this a go. should work, but I will likely still hit the pin protocol issue as it has to do with how the accumulator is evaluated. Would you be open to a pull request addressing this and adding parsing for some of the missing fields, even if not supported in the struct at the moment? I could merge it with this branch for the "best of both worlds" and some future-proofing.
> 
> All that should be included in that commit, apart from storing the unused fields they're just skipped.

Oops! I see that now.  I misread the code change, and i can understand not bothering to parse the unstored/unused fields, just thought since I had the code for the CBOR side, it would be a nice to have.

I have tested this patch.  It does function until it is time to unlock the token.  Now I seem to have run into something else.  I used the patch from #5 to allow the use of a pin, which now works on older tokens, but the unlock is failing on this new firmware.  I would assume I would see the same when leveraging this library when it came time to unlock the token with the pin.  Here's the output.
```
user@host:~$ (export RUST_BACKTRACE=1; export CTAP_PIN=1234; sudo -E ./hmac)
thread 'main' panicked at 'source slice length (32) does not match destination slice length (16)', /usr/local/rustup/toolchains/1.53.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs:3051:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::slice::<impl [T]>::copy_from_slice::len_mismatch_fail
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/slice/mod.rs:3044:13
   3: core::slice::<impl [T]>::copy_from_slice
             at /usr/local/rustup/toolchains/1.53.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs:3051:13
   4: ctap_hmac::cbor::ClientPinResponse::decode
             at /home/vscode/code/src/cbor.rs:385:21
   5: ctap_hmac::cbor::Request::decode
             at /home/vscode/code/src/cbor.rs:51:58
   6: ctap_hmac::FidoDevice::cbor
             at /home/vscode/code/src/lib.rs:552:9
   7: ctap_hmac::FidoDevice::unlock
             at /home/vscode/code/src/lib.rs:352:30
   8: hmac::main
             at /home/vscode/code/examples/hmac.rs:21:13
   9: core::ops::function::FnOnce::call_once
             at /usr/local/rustup/toolchains/1.53.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I will have a look into this myself as well, but any thoughts?

**Comment by shimunn** [comment]
>Oops! I see that now. I misread the code change, and i can understand not bothering to parse the unstored/unused fields, just >thought since I had the code for the CBOR side, it would be a nice to have.

It would be indeed but lets get the YubiKeys working at all first

> user@host:~$ (export RUST_BACKTRACE=1; export CTAP_PIN=1234; sudo -E ./hmac)
> thread 'main' panicked at 'source slice length (32) does not match destination slice length (16)', /usr/local/rustup/toolchains/1.53.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs:3051:13
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
>    1: core::panicking::panic_fmt
>              at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
>    2: core::slice::<impl [T]>::copy_from_slice::len_mismatch_fail
>              at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/slice/mod.rs:3044:13
>    3: core::slice::<impl [T]>::copy_from_slice
>              at /usr/local/rustup/toolchains/1.53.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs:3051:13
>    4: ctap_hmac::cbor::ClientPinResponse::decode
>              at /home/vscode/code/src/cbor.rs:385:21
>    5: ctap_hmac::cbor::Request::decode
>              at /home/vscode/code/src/cbor.rs:51:58
>    6: ctap_hmac::FidoDevice::cbor
>              at /home/vscode/code/src/lib.rs:552:9
>    7: ctap_hmac::FidoDevice::unlock
>              at /home/vscode/code/src/lib.rs:352:30
>    8: hmac::main
>              at /home/vscode/code/examples/hmac.rs:21:13
>    9: core::ops::function::FnOnce::call_once
>              at /usr/local/rustup/toolchains/1.53.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> ```
> 
> I will have a look into this myself as well, but any thoughts?

Seems like the spec allows for PIN tokens larger than 16 bytes which the new firmware makes use of, any multiple of 16 bytes should now be allowed as specified.

> I have tested this patch. It does function until it is time to unlock the token. Now I seem to have run into something else. I used the patch from #5 to allow the use of a pin, which now works on older tokens, but the unlock is failing on this new firmware. I would assume I would see the same when leveraging this library when it came time to unlock the token with the pin. Here's the output.

I have to confess I didn't read this part until now 😂 which is why I added the ability to read the PIN from stdin as well, which is probably better UX wise than an env var.

**Comment by geneerik** [comment]
> Seems like the spec allows for PIN tokens larger than 16 bytes which the new firmware makes use of, any multiple of 16 bytes should now be allowed as specified.
> 
> > I have tested this patch. It does function until it is time to unlock the token. Now I seem to have run into something else. I used the patch from #5 to allow the use of a pin, which now works on older tokens, but the unlock is failing on this new firmware. I would assume I would see the same when leveraging this library when it came time to unlock the token with the pin. Here's the output.
> 
> I have to confess I didn't read this part until now  which is why I added the ability to read the PIN from stdin as well, which is probably better UX wise than an env var.

Hah. Lol.  That works for me.  I just wanted a super simple way to do this and didnt want to hunt down a conditional to trigger stdin and manage user input validation; env seemed a super quick solution.  But i'll take the maintainer's solution any day!  I'll pull the new code and give it a go.  If it works (and i bet it does), I'll try a branch of fido2luks with this patch to verify its full fixed too.

**Comment by geneerik** [comment]
I tried this out @shimunn , but ended up with an error before I got a chance to authorize (touch) the token but after putting in the pin. verified my pin was correct and that i got a different error when it was wrong. Here's the output:
```
user@host:~$ (export RUST_BACKTRACE=1; sudo -E ./hmac)
FIDO2 PIN: 1234
Authorize using your device
thread 'main' panicked at 'Failed to request credential: FidoError(FidoError(   0: failure::backtrace::internal::InternalBacktrace::new
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/backtrace/internal.rs:46:44
   1: failure::backtrace::Backtrace::new
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/backtrace/mod.rs:121:35
   2: failure::context::Context<D>::new
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/context.rs:84:40
   3: <ctap_hmac::error::FidoError as core::convert::From<ctap_hmac::error::FidoErrorKind>>::from
             at /home/vscode/code/src/error.rs:113:19
      ctap_hmac::cbor::MakeCredentialResponse::decode
             at /home/vscode/code/src/cbor.rs:153:71
   4: ctap_hmac::cbor::Request::decode
             at /home/vscode/code/src/cbor.rs:45:42
   5: ctap_hmac::FidoDevice::cbor
             at /home/vscode/code/src/lib.rs:552:9
   6: ctap_hmac::FidoDevice::make_credential
             at /home/vscode/code/src/lib.rs:435:30
   7: <ctap_hmac::FidoDevice as ctap_hmac::extensions::hmac::HmacExtension>::make_hmac_credential
             at /home/vscode/code/src/extensions/hmac.rs:149:9
   8: hmac::main
             at /home/vscode/code/examples/hmac.rs:41:24
   9: core::ops::function::FnOnce::call_once
             at /usr/local/rustup/toolchains/1.53.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /usr/local/rustup/toolchains/1.53.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  11: std::rt::lang_start::{{closure}}
             at /usr/local/rustup/toolchains/1.53.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:49:18
  12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
      std::rt::lang_start_internal
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  13: std::rt::lang_start
             at /usr/local/rustup/toolchains/1.53.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:48:5
  14: main
  15: __libc_start_main
  16: <unknown>


Device returned error: CborError: 0x33: PIN authentication, pinAuth, verification failed.)

Error while decoding CBOR from device.)', examples/hmac.rs:43:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::expect
             at /usr/local/rustup/toolchains/1.53.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:997:23
   4: hmac::main
             at /home/vscode/code/examples/hmac.rs:41:24
   5: core::ops::function::FnOnce::call_once
             at /usr/local/rustup/toolchains/1.53.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Thoughts?  I'll keep looking too.

**Comment by geneerik** [comment]
I found the solution. The decrypt operation after receiving the encrypted pinUvAuthToken from the device locks the output to 16 bytes, when with the new firmware it will be 32 bytes. I will post a pull to the branch when I get a moment and try it in my fork of the fido2luks project asap.

**Comment by geneerik** [comment]
I have submitted a patch to this branch as pull #6 .  I'm going to try this code, which works with both 5.2.4 firmware and 5.4.3 firmware using the `hmac` tool, in a build of fido2luks and update that ticket as well. Please let me know if u have input on the pull request @shimunn

**Comment by geneerik** [comment]
Reporting back.  With the patch suggested in #6 combined with this one, fido2luks now works with the new 5.4.3 firmware as well as the old one.

**Comment by shimunn** [comment]
Works for me so I'm guessing we're all good here, thanks for your input :)

**Pull request merged**
